apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kubernetes-exec-with-golang
  name: kubernetes-exec-with-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernetes-exec-with-golang
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: kubernetes-exec-with-golang
    spec:
      hostname: kubernetes-exec-with-golang
      containers:
        - name: kubernetes-exec-with-golang
          tty: true
          image: kubernetes-exec-with-golang
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kubernetes-exec-with-golang
  name: kubernetes-exec-with-golang
spec:
  selector:
    run: kubernetes-exec-with-golang
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30066
---
